import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '../utils/trpc';
import HomeInput from '../components/HomeInput';
import HomeInfo from '../components/HomeInfo';
import Header from '../components/Header';
import { useEffect } from 'react';

const Home: NextPage = () => {
  useEffect(() => {}, []);

  return (
    <>
      <Head>
        <title>{`${process.env.NEXT_PUBLIC_APP_NAME as string} | Home`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          backgroundImage: 'url(/endless-clouds.svg)',
          backgroundRepeat: 'repeat',
        }}
        className="w-full bg-primary"
      >
        <main className="container flex flex-col items-center justify-center px-0 font-[Nunito] lg:px-0">
          <Header.Home />
          <HomeInput />
          <HomeInfo />
        </main>
      </div>
    </>
  );
};

export default Home;
