import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '../utils/trpc';
import HomeInput from '../components/HomeInput';
import HomeInfo from '../components/HomeInfo';
import Header from '../components/Header';
import { useEffect } from 'react';
import MyLinks from '../components/MyLinks';
import Loader from '../components/Loader';

const Home: NextPage = () => {
  const { data, status } = useSession();

  return (
    <>
      <Head>
        <title>{`${process.env.NEXT_PUBLIC_APP_NAME as string} | Home`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          backgroundImage: 'url(/endless-clouds.svg)',
          backgroundRepeat: 'repeat',
        }}
        className="w-full bg-primary"
      >
        {status === 'loading' ? (
          <Loader />
        ) : (
          <main className="container  px-0 font-[Nunito] lg:px-0">
            <Header.Home />
            <div className="flex flex-col items-center justify-center">
              <HomeInput />
              {data?.user?.name ? <MyLinks /> : <HomeInfo />}
            </div>
          </main>
        )}
      </div>
    </>
  );
};

export default Home;
