import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';

import { api } from '../utils/trpc';
import HomeInput from '../components/HomeInput';
import HomeInfo from '../components/HomeInfo';
import Header from '../components/Header';

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: 'from tRPC' });

  return (
    <>
      <Head>
        <title>{process.env.NEXT_PUBLIC_APP_NAME} | Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container flex flex-col items-center justify-center px-6 lg:px-0">
        <Header.Home />
        <HomeInput />
        <HomeInfo />
      </main>
    </>
  );
};

export default Home;
